### ISSUE TITLE
X connection error: authorization required

### ISSUE THREAD

**Issue by pieterdd** [flathub/io.github.slgobinath.SafeEyes#37]
I get this when I try to run the application:

```
$ flatpak run io.github.slgobinath.SafeEyes 
Traceback (most recent call last):
  File "/app/lib/python3.12/site-packages/safeeyes/safeeyes.py", line 102, in do_startup
    self.break_screen = BreakScreen(
                        ^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/safeeyes/ui/break_screen.py", line 47, in __init__
    self.display = Display()
                   ^^^^^^^^^
  File "/app/lib/python3.12/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.12/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/app/lib/python3.12/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
$ echo $XDG_SESSION_TYPE
wayland
```

**Comment by otuva** [comment]
Does this issue still persist?

**Comment by pieterdd** [comment]
I can no longer reproduce it :)
